apiVersion: v1
kind: Service
metadata:
  name: displaysocket
  namespace: default
spec:
  selector:
    app: displaysocket
  ports:
    - name: websocket
      port: 4001
      protocol: TCP
      targetPort: default
  type: ClusterIP